//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SomethingHere.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string City { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ShipperID { get; set; }
        public Nullable<int> OrderDetailID { get; set; }
        public Nullable<int> LoginUserID { get; set; }
    
        public virtual LoginUser LoginUser { get; set; }
        public virtual OrderDetails OrderDetails { get; set; }
        public virtual Shipper Shipper { get; set; }
    }
}
